### ISSUE TITLE
Create a Kotlin sample for Google Cloud Storage 

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/kotlin-samples#2]
Let's create a simple sample for calling Google Cloud Storage from Kotlin. [This sample](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/storage/cloud-client) exists for creating a bucket in Java. 

The sample should demonstrate the following:

- Create a bucket
- Upload an object
- Download an object

Use the vision sample for guidance. Command-line only is ok.

**Comment by wisdal** [comment]
The sample has been created.
