### ISSUE TITLE
[emojify-codelab]: Wrong (corp) link for "Enable App Engine Admin API"

### ISSUE THREAD

**Issue by SWalls** [GoogleCloudPlatform/kotlin-samples#41]
In the *Enable APIs* section of [Step 2](https://codelabs.developers.google.com/codelabs/cloud-kotlin-emojify/#1) of the codelab, the third "Enable" link is wrong. It's pointing to `pantheon.corp.google.com` when it presumably should point to `console.cloud.google.com`.

**Comment by bshaffer** [comment]
Thank you for reporting this!! This is now fixed.
