### ISSUE TITLE
[emojify-codelab]: Documentation points to google internal system

### ISSUE THREAD

**Issue by efalkenberg** [GoogleCloudPlatform/kotlin-samples#44]
The sample documentation (https://codelabs.developers.google.com/codelabs/cloud-kotlin-emojify/#1) links to an internal google-corp website:
<img width="1208" alt="screen shot 2019-03-04 at 2 48 30 pm" src="https://user-images.githubusercontent.com/10066236/53768198-f8154d80-3e8c-11e9-955c-08dc6b6dd141.png">

Clicking on the link redirects to this page:
<img width="1207" alt="screen shot 2019-03-04 at 2 48 43 pm" src="https://user-images.githubusercontent.com/10066236/53768218-0499a600-3e8d-11e9-99ad-ee518d598f3f.png">

**Comment by efalkenberg** [comment]
The correct URL should be https://console.cloud.google.com/apis/api/appengine.googleapis.com

**Comment by bshaffer** [comment]
Thank you for reporting this! This is now fixed.
