### ISSUE TITLE
[emojify-codelab]: gcloud CLI init is not explained

### ISSUE THREAD

**Issue by lgvalle** [GoogleCloudPlatform/kotlin-samples#49]
### Problem
In [step 6](https://codelabs.developers.google.com/codelabs/cloud-kotlin-emojify/#5) of the tutorial it asks to create an App Engine application using:

```bash
$ gcloud app create
```

but at that point, the user won't be logged in with `gcloud` if this is their first time using the sdk and **the command will fail**.

### Possible solution
There are two easy steps that need to happen before the App Engine application could be created:

**1. Authentication**
This will prompt the user to authenticate using their Google accounts with an easy to follow explanation
```bash
$ gcloud auth login
```

**2. Set project**
This will let the user select the project created in step 2 to be used by the gcloud sdk
```bash
$ gcloud config set project <PROJECT_ID>
```

**Comment by bshaffer** [comment]
Done! Thank you for filing this issue!
