### ISSUE TITLE
Where is the Java/Kotlin support?

### ISSUE THREAD

**Issue by ippersolar** [GoogleCloudPlatform/kotlin-samples#51]
I'm trying to create a function as described in the https://github.com/GoogleCloudPlatform/kotlin-samples/tree/master/functions , but once I try to deploy it with:
```
gcloud functions deploy test-http     --runtime=java8     --entry-point=HttpEndpoint.main     --trigger-http     --source=. 
```
, I always get: 
```
Problems:
Incorrect runtime value
]
```
Any ideas?

**Comment by ludoch** [comment]
Did you complete the first step of the tutorial 
"Sign up here to request alpha access." ?
Let us know.

**Comment by sergiofigueras** [comment]
Hello ludoch,

Thanks for pointing this out. We've done it.

Thanks,

Sergio
