### ISSUE TITLE
How to Run Cron Jobs in Kotlin Ktor

### ISSUE THREAD

**Issue by AdamSHurwitz** [GoogleCloudPlatform/kotlin-samples#56]
**Is there a way to run Cron Jobs with [Ktor][1]? My end objective is to host a Cron Job written with Kotlin for the [Coinverse app's](https://play.google.com/store/apps/details?id=app.coinverse) backend service to populate data.**
 
I'm currently hosting multiple Java *.jar* apps written in Kotlin on AppEngine. I'm looking to refactor these apps into Ktor apps on AppEngine with a [Cron Job][2] for scheduled tasks, as the *.jar* apps have more issues with dependencies. 
 
I'm looking for Ktor's equivalent to Cloud Functions' [built-in implementation][3] for Cron Jobs with JavaScript. 
 
    functions.pubsub.schedule
 
*Back-up option:* **Is this alpha/beta available?** If Ktor does not have this feature and I want to keep the code in Kotlin, Google has an alpha, [Using Kotlin with Google Cloud Functions][4]. It appears Kotlin + Cloud Functions' built-in implementation could be used with this approach. 

I've created a corresponding [StackOverflow post](https://stackoverflow.com/questions/59516599/how-to-run-cron-jobs-in-kotlin-ktor).

  [1]: https://ktor.io/
  [2]: https://cloud.google.com/appengine/docs/standard/java/config/cron-yaml
  [3]: https://firebase.googleblog.com/2019/04/schedule-cloud-functions-firebase-cron.html
  [4]: https://github.com/GoogleCloudPlatform/kotlin-samples/tree/master/functions

**Comment by bshaffer** [comment]
@AdamSHurwitz Yes, use the GA [Java 11 Appengine Runtime](https://cloud.google.com/appengine/docs/standard/java11) (sorry for the late reply)

It seems your other question [has been answered](https://stackoverflow.com/questions/59516599/how-to-run-cron-jobs-in-kotlin-ktor)

**Comment by bshaffer** [comment]
@AdamSHurwitz Yes, use this signup form to request access to [Cloud Functions for Java 11](https://docs.google.com/forms/d/e/1FAIpQLScC98jGi7CfG0n3UYlj7Xad8XScvZC8-BBOg7Pk3uSZx_2cdQ/viewform)

It seems your other question [has been answered](https://stackoverflow.com/questions/59516599/how-to-run-cron-jobs-in-kotlin-ktor)
