### ISSUE TITLE
Not able to use the project to deploy kotlin project to cloud run

### ISSUE THREAD

**Issue by trnchawla** [GoogleCloudPlatform/kotlin-samples#59]
Expand all | Collapse all{
 insertId: "5e54c1ae00030aa84bd7cf47"  
 labels: {
  instanceId: "00bf4bf02d2112b83366440937a7f764ba2a4ef55eeb0ec7c4d2f58330367035d3db3321679ea9ba7e6e584cbec2525f6cd4cb90040c40eb13d621458f60c2"   
 }
 logName: "projects/dummy-pos-certi2/logs/run.googleapis.com%2Fstderr"  
 receiveTimestamp: "2020-02-25T06:41:50.406969252Z"  
 resource: {
  labels: {
   configuration_name: "ssl-server"    
   location: "us-east1"    
   project_id: "dummy-pos-certi2"    
   revision_name: "ssl-server-00003-pog"    
   service_name: "ssl-server"    
  }
  type: "cloud_run_revision"   
 }
 textPayload: "Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at au.com.orient.MainKt.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more"  
 timestamp: "2020-02-25T06:41:50.199336Z"  
}

**Comment by bshaffer** [comment]
This is not enough information for me to do anything. Please see the code [here](https://github.com/knative/docs/tree/master/docs/serving/samples/hello-world/helloworld-kotlin)  and the tutorial [here](https://cloud.google.com/run/docs/quickstarts/build-and-deploy) for deploying Kotlin to Cloud Run
